# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - potential-octo-broccoli

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with SBT
      run: sbt compile run

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'potential-octo-broccoli'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4a3d687afe994f4f820c1786fe1925fc }}
        package: '${{ github.workspace }}/target/*.jar'